In [1]:
import numpy as np
import pandas as pd

In [2]:
bnpjamaat = pd.read_excel('bnpjamaat.xlsx',index_col=0)

In [3]:
bnpjamaat.head()

,usernameTweet,text,url,nbr_retweet,nbr_favorite,nbr_reply,date,time,has_media,medias,is_reply,is_retweet,user_id,place,country
ID,,,,,,,,,,,,,,,
1027070401451570048,MAlamHanif,A group of people still blocking the roads eve...,/MAlamHanif/status/1027070401451573248,10,61,6,2018-08-08,11:54:00,NaN,NaN,False,False,3245437351,NaN,NaN
1026808311063049984,MAlamHanif,# Bangladesh govt already accepted the 9 deman...,/MAlamHanif/status/1026808311063052289,12,66,3,2018-08-07,18:32:00,NaN,NaN,False,False,3245437351,NaN,NaN
1026558533872089984,DeadTonmoy,A non political movement demanding #SafeRoadsF...,/DeadTonmoy/status/1026558533872099335,4,28,3,2018-08-07,02:00:00,NaN,NaN,False,False,2304606750,NaN,NaN
1026471854062450048,DeadTonmoy,The #Bangladesh govt already accepted the 9 de...,/DeadTonmoy/status/1026471854062456832,7,18,3,2018-08-06,20:15:00,NaN,NaN,False,False,2304606750,NaN,NaN
1026472749441510016,PijonZimtuj,The #Bangladesh govt already accepted the 9 de...,/PijonZimtuj/status/1026472749441511424,2,5,3,2018-08-06,20:19:00,NaN,NaN,False,False,3003752936,NaN,NaN

In [4]:
bnpjamaat.tail()

,usernameTweet,text,url,nbr_retweet,nbr_favorite,nbr_reply,date,time,has_media,medias,is_reply,is_retweet,user_id,place,country
ID,,,,,,,,,,,,,,,
1027903194427340032,tauhidul97,# BNPjamaat Conspirators tried to turn the stu...,/tauhidul97/status/1027903194427342853,0,0,0,2018-08-10,19:03:00,NaN,NaN,False,False,4409846180,NaN,NaN
1027903975310240000,Tareqjkkniu,# BNPjamaat Conspirators tried to turn the stu...,/Tareqjkkniu/status/1027903975310249986,0,0,0,2018-08-10,19:06:00,NaN,NaN,False,False,324809827,NaN,NaN
1027910089829760000,chiranjibamit,Conspiracy in the shadow of student movement.....,/chiranjibamit/status/1027910089829765126,0,0,0,2018-08-10,19:30:00,NaN,NaN,False,False,583007948,NaN,NaN
1027938810435270016,SyedTito71,Conspiracy in the shadow of student movement.....,/SyedTito71/status/1027938810435272704,0,0,0,2018-08-10,21:24:00,NaN,NaN,False,False,863765193641401984,NaN,NaN
1028279863038200064,FM_Pavel3,# BNPjamaat Conspirators tried to turn the stu...,/FM_Pavel3/status/1028279863038205953,0,0,0,2018-08-11,19:59:00,NaN,NaN,False,False,993912753998913024,NaN,NaN

In [5]:
len(bnpjamaat)

2737

In [6]:
len(bnpjamaat['user_id'].unique())

240

In [7]:
len(bnpjamaat['usernameTweet'].unique())

240

In [8]:
type(bnpjamaat['user_id'].unique())

numpy.ndarray

In [9]:
user_id_lst = list(bnpjamaat['user_id'].unique())

In [10]:
follower = pd.read_excel('follower_followed.xlsx',index_col=0)
follower_bj = follower.loc[user_id_lst].copy()
follower_bj.dropna(inplace=True)
follower = list(follower_bj.index)


followed = pd.read_excel('follower_followed.xlsx',index_col=1)
followed_bj = followed.loc[user_id_lst].copy()
followed_bj.dropna(inplace=True)
followed = list(followed_bj.index)


followed = list(set(followed))
follower = list(set(follower))

c:\users\alvira~1\deeple~1\lib\site-packages\ipykernel_launcher.py:2: FutureWarning:
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike

c:\users\alvira~1\deeple~1\lib\site-packages\ipykernel_launcher.py:8: FutureWarning:
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike

In [11]:
bj_dict = {}
for i in range(len(followed)):
    if followed[i] in follower:
        bj_dict[followed[i]] = True

        
for i in range(len(follower)):
    if follower[i] in followed:
        bj_dict[follower[i]] = True

In [16]:
len(followed)

113

In [17]:
len(follower)

117

In [13]:
len(bj_dict)

112

In [14]:
all_bj = list(bj_dict.keys())
not_in_bj = [followed[i] for i in range(len(followed)) if followed[i] not in all_bj]
not_in_bj.extend([follower[i] for i in range(len(follower)) if follower[i] not in all_bj])
not_in_bj

[425347635, 3012293286, 3010980588, 3023364448, 3021219682, 3021166457]

In [18]:
##############step hasina#######################

In [19]:
stepdownhasina = pd.read_excel('stepdownhasina.xlsx',index_col=0)

stepdownhasina.head()

user_id_lst = list(stepdownhasina['user_id'].unique())

len(user_id_lst)

27

In [20]:
follower = pd.read_excel('follower_followed.xlsx',index_col=0)
follower_step_hasina = follower.loc[user_id_lst].copy()
follower_step_hasina.dropna(inplace=True)
follower = list(follower_step_hasina.index)

followed = pd.read_excel('follower_followed.xlsx',index_col=1)
followed_step_hasina = followed.loc[user_id_lst].copy()
followed_step_hasina.dropna(inplace=True)
followed = list(followed_step_hasina.index)

followed = list(set(followed))
follower = list(set(follower))

In [21]:
step_hasina_dict = {}
for i in range(len(followed)):
    if followed[i] in follower:
        step_hasina_dict[followed[i]] = True

        
for i in range(len(follower)):
    if follower[i] in followed:
        step_hasina_dict[follower[i]] = True

In [22]:
len(step_hasina_dict)

27

In [23]:
all_step_hasina = list(step_hasina_dict.keys())
not_in_step_hasina = [followed[i] for i in range(len(followed)) if followed[i] not in all_step_hasina]
not_in_step_hasina.extend([follower[i] for i in range(len(follower)) if follower[i] not in all_step_hasina])
not_in_step_hasina

[]

In [24]:
############ shahjahanmustgo################

In [25]:
shahjahan = pd.read_excel('shahjahanmustgo.xlsx',index_col=0)

shahjahan.head()

,usernameTweet,text,url,nbr_retweet,nbr_favorite,nbr_reply,date,time,has_media,medias,is_reply,is_retweet,user_id,place,country
ID,,,,,,,,,,,,,,,
1025406947942494208,basherkella,Will you take dead body? Dead bodies of studen...,/basherkella/status/1025406947942494208,90,220,5,2018-08-03 21:44:02,2018-08-03 21:44:02,NaN,NaN,False,False,1176335252,NaN,NaN
1025406947942494208,basherkella,Will you take dead body? Dead bodies of studen...,/basherkella/status/1025406947942494208,89,219,5,2018-08-03 21:44:02,2018-08-03 21:44:02,NaN,NaN,False,False,1176335252,NaN,NaN
1026069370324353024,basherkella,Attack on @AP photojournalist AM Ahad: See how...,/basherkella/status/1026069370324353024,42,86,5,2018-08-05 17:36:15,2018-08-05 17:36:15,NaN,NaN,False,False,1176335252,NaN,NaN
1026069370324353024,basherkella,Attack on @AP photojournalist AM Ahad: See how...,/basherkella/status/1026069370324353024,42,84,5,2018-08-05 17:36:15,2018-08-05 17:36:15,NaN,NaN,False,False,1176335252,NaN,NaN
1024610449961013248,RahatAdnan17,Brave school and college students of #Banglade...,/RahatAdnan17/status/1024610449961013248,131,180,3,2018-08-01 16:59:02,2018-08-01 16:59:02,NaN,NaN,False,False,945521215808053248,NaN,NaN

In [26]:
user_id_lst = list(shahjahan['user_id'].unique())

len(user_id_lst)

61

In [27]:
follower = pd.read_excel('follower_followed.xlsx',index_col=0)
follower_shahjahan = follower.loc[user_id_lst].copy()
follower_shahjahan.dropna(inplace=True)
follower = list(follower_shahjahan.index)

followed = pd.read_excel('follower_followed.xlsx',index_col=1)
followed_shahjahan = followed.loc[user_id_lst].copy()
followed_shahjahan.dropna(inplace=True)
followed = list(followed_shahjahan.index)

followed = list(set(followed))
follower = list(set(follower))

c:\users\alvira~1\deeple~1\lib\site-packages\ipykernel_launcher.py:2: FutureWarning:
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike

c:\users\alvira~1\deeple~1\lib\site-packages\ipykernel_launcher.py:7: FutureWarning:
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  import sys

In [28]:
shahjahan_dict = {}
for i in range(len(followed)):
    if followed[i] in follower:
        shahjahan_dict[followed[i]] = True

        
for i in range(len(follower)):
    if follower[i] in followed:
        shahjahan_dict[follower[i]] = True

In [29]:
len(shahjahan_dict)

56

In [30]:
all_shahjahan = list(shahjahan_dict.keys())

not_in_shahjahan = [followed[i] for i in range(len(followed)) if followed[i] not in all_shahjahan]

not_in_shahjahan.extend([follower[i] for i in range(len(follower)) if follower[i] not in all_shahjahan])

not_in_shahjahan

[804343111036059649,
 1014447359093137409,
 757248545724301312,
 340951989,
 1019699812390850560]

In [31]:
#############save democracy ##############

In [32]:
savedemocracy = pd.read_excel('savedemocracy.xlsx',index_col=0)

savedemocracy.head()

,usernameTweet,text,url,nbr_retweet,nbr_favorite,nbr_reply,date,time,has_media,medias,is_reply,is_retweet,user_id,place,country
ID,,,,,,,,,,,,,,,
1040871818083483649,haidersuman,# Fascist #SheikhHasina government has destroy...,/haidersuman/status/1040871818083483649,3,5,2,2018-09-15 13:55:54,2018-09-15 13:55:54,NaN,NaN,True,False,1405581504,NaN,NaN
1050744628331175936,haidersuman,# FreeKhaledaZia #FreeAllPoliticalPrisoners #F...,/haidersuman/status/1050744628331175936,2,4,2,2018-10-12 19:46:55,2018-10-12 19:46:55,NaN,NaN,False,False,1405581504,NaN,NaN
1040903604347920384,Omihasa90445588,# Fascist #SheikhHasina government has destroy...,/Omihasa90445588/status/1040903604347920384,6,10,1,2018-09-15 16:02:12,2018-09-15 16:02:12,NaN,NaN,False,False,1035573524700655616,NaN,NaN
1055031045014339584,kostto2,"In front of the next election, the National Un...",/kostto2/status/1055031045014339584,2,4,1,2018-10-24 15:39:37,2018-10-24 15:39:37,NaN,NaN,False,False,872763194049212423,NaN,NaN
1042004088727064577,Mujahid5558,# FreeKhaledaZia #FreeShahidulAlam #FreeALLPol...,/Mujahid5558/status/1042004088727064577,0,3,1,2018-09-18 16:55:08,2018-09-18 16:55:08,NaN,NaN,True,False,939544546223915009,NaN,NaN

In [33]:
user_id_lst = list(savedemocracy['user_id'].unique())

len(user_id_lst)

18

In [34]:
follower = pd.read_excel('follower_followed.xlsx',index_col=0)
follower_save_democracy = follower.loc[user_id_lst].copy()
follower_save_democracy.dropna(inplace=True)
follower = list(follower_save_democracy.index)

followed = pd.read_excel('follower_followed.xlsx',index_col=1)
followed_save_democracy = followed.loc[user_id_lst].copy()
followed_save_democracy.dropna(inplace=True)
followed = list(followed_save_democracy.index)

followed = list(set(followed))
follower = list(set(follower))

c:\users\alvira~1\deeple~1\lib\site-packages\ipykernel_launcher.py:7: FutureWarning:
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  import sys

In [35]:
save_democracy_dict = {}
for i in range(len(followed)):
    if followed[i] in follower:
        save_democracy_dict[followed[i]] = True

        
for i in range(len(follower)):
    if follower[i] in followed:
        save_democracy_dict[follower[i]] = True

In [36]:
len(save_democracy_dict)

15

In [37]:
all_save_democracy = list(save_democracy_dict.keys())

not_in_save_democracy = [followed[i] for i in range(len(followed)) if followed[i] not in all_save_democracy]

not_in_save_democracy.extend([follower[i] for i in range(len(follower)) if follower[i] not in all_save_democracy])

not_in_save_democracy

[794139252225232896, 949076810, 1025462684706201600]

In [38]:
############stophoax#############

In [39]:
stophoax = pd.read_excel('stophoax.xlsx',index_col=0)

stophoax.head()

,usernameTweet,text,url,nbr_retweet,nbr_favorite,nbr_reply,date,time,has_media,medias,is_reply,is_retweet,user_id,place,country
ID,,,,,,,,,,,,,,,
1027070401451570048,MAlamHanif,A group of people still blocking the roads eve...,/MAlamHanif/status/1027070401451573248,10,61,6,2018-08-08,11:54:00,NaN,NaN,False,False,3245437351,NaN,NaN
1026808311063049984,MAlamHanif,# Bangladesh govt already accepted the 9 deman...,/MAlamHanif/status/1026808311063052289,12,66,3,2018-08-07,18:32:00,NaN,NaN,False,False,3245437351,NaN,NaN
1026471854062450048,DeadTonmoy,The #Bangladesh govt already accepted the 9 de...,/DeadTonmoy/status/1026471854062456832,7,18,3,2018-08-06,20:15:00,NaN,NaN,False,False,2304606750,NaN,NaN
1026472749441510016,PijonZimtuj,The #Bangladesh govt already accepted the 9 de...,/PijonZimtuj/status/1026472749441511424,2,5,3,2018-08-06,20:19:00,NaN,NaN,False,False,3003752936,NaN,NaN
1026981334546300032,Maksud_15,A group of people still blocking the roads eve...,/Maksud_15/status/1026981334546309121,0,2,3,2018-08-08,06:00:00,NaN,NaN,False,False,3011568776,NaN,NaN

In [40]:
user_id_lst = list(stophoax['user_id'].unique())

len(user_id_lst)

225

In [41]:
follower = pd.read_excel('follower_followed.xlsx',index_col=0)
follower_stop_hoax = follower.loc[user_id_lst].copy()
follower_stop_hoax.dropna(inplace=True)
follower = list(follower_stop_hoax.index)

followed = pd.read_excel('follower_followed.xlsx',index_col=1)
followed_stop_hoax = followed.loc[user_id_lst].copy()
followed_stop_hoax.dropna(inplace=True)
followed = list(followed_stop_hoax.index)

followed = list(set(followed))
follower = list(set(follower))

c:\users\alvira~1\deeple~1\lib\site-packages\ipykernel_launcher.py:2: FutureWarning:
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike

c:\users\alvira~1\deeple~1\lib\site-packages\ipykernel_launcher.py:7: FutureWarning:
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  import sys

In [42]:
stop_hoax_dict = {}
for i in range(len(followed)):
    if followed[i] in follower:
        stop_hoax_dict[followed[i]] = True

        
for i in range(len(follower)):
    if follower[i] in followed:
        stop_hoax_dict[follower[i]] = True

In [43]:
len(stop_hoax_dict)

105

In [44]:
all_stop_hoax = list(stop_hoax_dict.keys())
not_in_stop_hoax = [followed[i] for i in range(len(followed)) if followed[i] not in all_stop_hoax]
not_in_stop_hoax.extend([follower[i] for i in range(len(follower)) if follower[i] not in all_stop_hoax])
not_in_stop_hoax

[425347635, 3012293286, 3010980588, 3023364448, 3021219682, 3021166457]

In [45]:
############shahidul##############

In [46]:
shahidul = pd.read_excel('shahidul.xlsx',index_col=0)

shahidul.head()

,usernameTweet,text,url,nbr_retweet,nbr_favorite,nbr_reply,date,time,has_media,medias,is_reply,is_retweet,user_id,place,country
ID,,,,,,,,,,,,,,,
1027131769693200000,Shehla_Rashid,Strongly condemn Bangladesh govt's crackdown o...,/Shehla_Rashid/status/1027131769693200384,162,840,44,2018-08-08,15:57:00,NaN,NaN,False,False,194022170,NaN,NaN
1050045531353939968,RupaHuq,Case of photo-journalist incarcerated and tort...,/RupaHuq/status/1050045531353944064,198,429,31,2018-10-10,21:28:00,NaN,NaN,False,False,706747004,NaN,NaN
1032074533191049984,sharonstone,This is Shahidul Alam. A call to action for th...,/sharonstone/status/1032074533191053312,149,360,30,2018-08-22,07:18:00,NaN,NaN,False,False,1949906586,NaN,NaN
1026735529914759936,ReallySwara,# Bangladesh #FreeShahidulAlam https:// twitte...,/ReallySwara/status/1026735529914769413,23,146,27,2018-08-07,13:43:00,NaN,NaN,False,False,1546101560,NaN,NaN
1065016174935709952,sharonstone,Shahidul is out!!!! Thank you to all who helpe...,/sharonstone/status/1065016174935719936,24,184,24,2018-11-21,04:56:00,NaN,NaN,False,False,1949906586,NaN,NaN

In [47]:
user_id_lst = list(shahidul['user_id'].unique())

len(user_id_lst)

1961

In [48]:
follower = pd.read_excel('follower_followed.xlsx',index_col=0)
follower_shahidul = follower.loc[user_id_lst].copy()
follower_shahidul.dropna(inplace=True)
follower = list(follower_shahidul.index)

followed = pd.read_excel('follower_followed.xlsx',index_col=1)
followed_shahidul = followed.loc[user_id_lst].copy()
followed_shahidul.dropna(inplace=True)
followed = list(followed_shahidul.index)

followed = list(set(followed))
follower = list(set(follower))

c:\users\alvira~1\deeple~1\lib\site-packages\ipykernel_launcher.py:2: FutureWarning:
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike

c:\users\alvira~1\deeple~1\lib\site-packages\ipykernel_launcher.py:7: FutureWarning:
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  import sys

In [49]:
shahidul_dict = {}
for i in range(len(followed)):
    if followed[i] in follower:
        shahidul_dict[followed[i]] = True

        
for i in range(len(follower)):
    if follower[i] in followed:
        shahidul_dict[follower[i]] = True

In [50]:
len(shahidul_dict)

999

In [51]:
all_shahidul = list(shahidul_dict.keys())
not_in_shahidul = [followed[i] for i in range(len(followed)) if followed[i] not in all_shahidul]
not_in_shahidul.extend([follower[i] for i in range(len(follower)) if follower[i] not in all_shahidul])
not_in_shahidul

[58386439,
 2314672190,
 2647091335,
 203985048,
 1663170722,
 119410994,
 1183383930,
 2828448192,
 1665534414,
 3268383253,
 30442011,
 979053284,
 347974406,
 1672846104,
 3131605787,
 452877096,
 2505548600,
 437308264,
 3305173903,
 76383158,
 2914167743,
 15008782,
 293975071,
 2215474214,
 2890484790,
 141569093,
 31421672,
 453582151,
 60886384,
 178394509,
 420949439,
 2714318316,
 12629592,
 2487490152,
 2930935453,
 545840826,
 2996703032,
 3441244039,
 43116435,
 917250560880812032,
 73072650,
 142188566,
 36937757,
 3186941990,
 310157353,
 928211060,
 205258928,
 1139400883,
 85516520,
 2609504528,
 84648330,
 2807734682,
 2771050913,
 263381446,
 99992010,
 1454039550,
 2464203284,
 3281461783,
 868868665,
 1443480134,
 192488009,
 3328139989,
 162374410,
 1260241680,
 85033744,
 949076810,
 166847405,
 1670906802,
 1968145459,
 2899280976,
 277611636,
 91038840,
 62571679,
 2816877752,
 77866185,
 1465091322,
 315655427,
 2875737359,
 2214716689,
 2929829217,
 52495721,
 91088260,
 4911580550,
 2906801544,
 1572578707,
 550512020,
 2865456554,
 341853633,
 167454150,
 22177242,
 3139839480,
 745915908,
 88671774,
 3106129501,
 3761415808,
 236938915,
 93898426,
 1288718017,
 115164876,
 130475723,
 2424104784,
 2438465366,
 141846366,
 249210747,
 1481197459,
 40306686,
 26707983,
 14264396,
 439126092,
 488655267,
 3592260022,
 1478404568,
 392169967,
 932194806,
 3329501691,
 3189713544,
 24840898,
 2723949325,
 86985550,
 3007318923,
 266652562,
 184896426,
 4286671814,
 2801929188,
 2199161843,
 277507059,
 3235908626,
 16632884,
 3233524868,
 343452900,
 4025527558,
 2532453650,
 90828056,
 736079156,
 1607658841,
 323079520,
 135179619,
 228404593,
 1625304458,
 1371934110,
 1042927069,
 62410212,
 216976871,
 393801256,
 2162232880,
 751136353,
 4650651313,
 498790077,
 613207797,
 1001459510,
 2785177416,
 792153960,
 4721684413,
 215740360,
 732552762974720000,
 993168433259819008,
 1025765323624960000,
 207073281,
 167014451,
 559796310,
 2513555564,
 2290995365,
 391237800,
 161657051,
 2411286751,
 281825517,
 342757680,
 145174837,
 2408894780,
 4300476733,
 423170430,
 85143999,
 104444352,
 254185925,
 466268617,
 4620521964,
 3254342148,
 388682261,
 14463529,
 4451676925,
 4329902907,
 2831954853,
 1445884872,
 3181605836,
 323105818,
 2210182182,
 326751271,
 149615673,
 2563658942,
 4430607552,
 1161286856,
 26465492,
 60912876,
 2160014649,
 2282591550,
 2591774048,
 3025581433,
 21933,
 175330765,
 1692931548,
 187635203,
 3292206619,
 365909539,
 847877689,
 21018188,
 4657190480,
 3010369129,
 165041785,
 190207623,
 2698729136,
 1404597979,
 429659882,
 512145139,
 2523551481,
 147109627,
 44594957,
 757176080,
 547804988,
 1325102965,
 1694627744,
 340441002,
 188733376,
 1493964738,
 2734307297,
 93976567,
 3033167871,
 103004199,
 484128836,
 2217883740,
 59177059,
 79698050,
 115464366,
 41629878,
 1397749964,
 2988890336,
 297924837,
 2267060464,
 4384708852,
 622778622,
 1190770963,
 1731828008,
 65345864,
 1195301268,
 1676335537,
 120650168,
 3031022021,
 26679759,
 134371791,
 4026595853,
 335968785,
 460470836,
 31439452,
 11803262,
 264141540,
 340712175,
 255810393,
 886520666,
 179051387,
 45792138,
 2736274325,
 565377950,
 2417671076,
 722131908,
 1102732231,
 2419620836,
 76708850,
 333421585,
 1046354994,
 311802940,
 451968085,
 732134520,
 789937322,
 562117824,
 87088335,
 1405123807,
 1144388868,
 49257796,
 170155339,
 416529790,
 2585492893,
 2933087659,
 2765012396,
 140393949,
 3062267371,
 1259118085,
 3305471503,
 2699001393,
 126607068,
 3815063295,
 1017323306,
 135552842,
 623206224,
 2362851169,
 3081961316,
 3098361703,
 86818690,
 48848772,
 1962516367,
 81158043,
 2177433511,
 4054630333,
 1728274398,
 625827812]